cargo-features = ["workspace-inheritance"]

[package]
name = "hyperlane-base"
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
bs58.workspace = true
color-eyre = { workspace = true, optional = true }
config.workspace = true
convert_case.workspace = true
derive-new.workspace = true
ed25519-dalek.workspace = true
ethers.workspace = true
eyre.workspace = true
fuels.workspace = true
futures-util.workspace = true
itertools.workspace = true
paste.workspace = true
prometheus.workspace = true
rocksdb.workspace = true
serde.workspace = true
serde_json.workspace = true
static_assertions.workspace = true
tempfile = { workspace = true, optional = true }
thiserror.workspace = true
tokio = { workspace = true, features = ["rt", "macros", "parking_lot"] }
tracing-error.workspace = true
tracing-futures.workspace = true
tracing-subscriber = { workspace = true, features = ["json", "ansi"] }
tracing.workspace = true
warp.workspace = true

backtrace = { workspace = true, optional = true }
backtrace-oneline = { path = "../utils/backtrace-oneline", optional = true }

ethers-prometheus = { path = "../ethers-prometheus", features = ["serde"] }
hyperlane-core = { path = "../hyperlane-core", features = ["agent"] }
hyperlane-ethereum = { path = "../chains/hyperlane-ethereum" }
hyperlane-fuel = { path = "../chains/hyperlane-fuel" }
hyperlane-sealevel = { path = "../chains/hyperlane-sealevel" }
hyperlane-test = { path = "../hyperlane-test" }

# dependency version is determined by etheres
rusoto_core = "*"
rusoto_kms = "*"
rusoto_s3 = "*"
rusoto_sts = "*"

[dev-dependencies]
color-eyre.workspace = true
tempfile.workspace = true
walkdir.workspace = true

[features]
default = ["oneline-errors", "color-eyre"]
oneline-eyre = ["backtrace-oneline", "backtrace"]
oneline-errors = ["oneline-eyre"]
test-utils = ["dep:tempfile"]
