[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'forge-cache'
allow_paths = ["../node_modules"]
solc = '0.8.15'
optimizer = true
optimizer_runs = 999_999

[profile.ci]
verbosity = 4

[rpc_endpoints]
mainnet = "https://rpc.ankr.com/eth"
optimism = "https://rpc.ankr.com/optimism"
