cargo-features = ["workspace-inheritance"]

[package]
name = "hex"
version = "0.1.0"
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
crunchy.workspace = true
