[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
allow_paths = ["../../node_modules", "../../solidity"]
solc = '0.8.15'
optimizer = true
optimizer_runs = 999_999

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
