[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
allow_paths = ["../../node_modules", "../../solidity"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
