cargo-features = ["workspace-inheritance"]

[package]
name = "backtrace-oneline"
version = "0.1.0"
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
backtrace.workspace = true
derive-new.workspace = true