name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - tvl

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log into registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./rust
          file: ./rust/Dockerfile
          push: true
          tags: ghcr.io/${{github.repository}}:${{ github.sha }}
